services:
  app:
    build: .
    restart: always
    command: >
      php artisan octane:frankenphp
      --host=0.0.0.0
      --port=8000
      --workers=auto
      --max-requests=500

    environment:
      SERVER_NAME: ${APP_URL:-:80}
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-sail}
      DB_PASSWORD: ${DB_PASSWORD:-password}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dokploy-network
    ports:
      - '8000:8000'

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-sail}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME:-sail} -d ${DB_DATABASE:-laravel}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dokploy-network

volumes:
  db-data:

networks:
  dokploy-network:
    driver: bridge